server:
  port: 8099

spring:
  application:
    name: parking-service
  config:
    import: configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/parkingdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/